version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - 7000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plugindb
    networks:
      - advisenetwork
networks:
  advisenetwork: